### ISSUE TITLE
Support BenchmarkDotNet

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#118]
The [vanilla  BenchmarkDotNet sample code](http://benchmarkdotnet.org/Guides/GettingStarted.htm) fails with `Access to the path 'C:\WINDOWS\system32\BenchmarkDotNet.Artifacts' is denied.`

```cs
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Md5VsSha256
{
    private const int N = 10000;
    private readonly byte[] data;

    private readonly SHA256 sha256 = SHA256.Create();
    private readonly MD5 md5 = MD5.Create();

    public Md5VsSha256()
    {
        data = new byte[N];
        new Random(42).NextBytes(data);
    }

    [Benchmark]
    public byte[] Sha256() => sha256.ComputeHash(data);

    [Benchmark]
    public byte[] Md5() => md5.ComputeHash(data);
}

BenchmarkRunner.Run<Md5VsSha256>();
```

Full stack trace:
```   
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
at System.IO.Directory.CreateDirectory(String path)
at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
at async Program.<Initialize>(?) in :line 61
```

**Comment by aelij** [comment]
I’m afraid this one is a bit out of scope for RP. BenchmarkDotNet runs using its own host processes, and integrating it would be a pain.

**Comment by aelij** [comment]
Seems like you can run it inproc:

```csharp
BenchmarkRunner.Run<Md5VsSha256>(
    DefaultConfig.Instance
        .With(Job.Default
            .With(InProcessToolchain.Instance)));
```

**Comment by ohadschn** [comment]
Ah, cool workaround. Regarding the original issue, I was thinking more along the lines of figuring out why it tries to create its folder in `C:\WINDOWS\system32` (working folder maybe?). If you can let it run in some folder you control it shouldn't have permission issues...

**Comment by aelij** [comment]
On my machine it uses the RoslynPad document directory, but I get a null ref exception. Also, need I remind you of a certain image used when one posts an exception without a stack trace? ;)

**Comment by ohadschn** [comment]
Apparently you do :)
Edited OP with full stack trace.

**Comment by aelij** [comment]
I'm closing this as the workaround is fine for now. If you want to investigate why the OOP version doesn't work, you're more than welcome ;)

**Comment by rs38** [comment]
you may be interested in using **MeasureIt** instead, which works quite nice and simple with roslynPad:
Simply add the nuget Package and Namespace:

```
#r "$NuGet\MeasureIt.exe\0.2.2\lib\net20\MeasureIt.exe"

using PerformanceMeasurement;

LinqPadUX.Measure.Action("decimal",new Action(()=>
{
    var l = new List<decimal>();
    for (int i = 0; i < 1000; i++)
    {
     l.Add(i);  
    }
})).Dump();
```

It hasn't been updated for a while, but worked for me.

**Comment by DamianSuess** [comment]
For any future readers of this post:

As per the author's post in #285 the BenchmarkDotNet example can be retrofitted with the `InProcessConfig` and view the results in the newly created `BenchmarkDotNet.Artifacts` folder. Great add @aelij!!

```cs
#r "nuget:BenchmarkDotNet/0.13.4"

using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Toolchains.InProcess.NoEmit;
using System.Buffers;

_ = BenchmarkRunner.Run<Md5VsSha256>();

[Config(typeof(InProcessConfig))]
[MemoryDiagnoser]
// [RPlotExporter]    // Generate R script for graph creation
public class Md5VsSha256
{
    private SHA256 sha256 = SHA256.Create();
    private MD5 md5 = MD5.Create();
    private byte[] data;

    [Params(1000, 10000)]
    public int N;
    
    [GlobalSetup]
    public void Setup()
    {
        data = new byte[N];
        new Random(42).NextBytes(data);
    }

    [Benchmark]
    public byte[] Sha256() => sha256.ComputeHash(data);

    [Benchmark]
    public byte[] Md5() => md5.ComputeHash(data);
}

public class InProcessConfig : ManualConfig
{
    public InProcessConfig()
    {
        AddJob(Job.MediumRun
            .WithToolchain(InProcessNoEmitToolchain.Instance));
    }
}
```
