### ISSUE TITLE
v13 Issues

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#119]
Yay new Version finally!!

How do I set STAThread since I use some gui elements and they don't work without this attribute and it seems no longer set by default?

Nice addition of these warnings, however if that warning is in a different script, and I double click it, it sets pointer in the current file, and I can't tell which script has it.

However, I get an error (well red strip at the bottom), it doesn't seem to be critical since it works, and in some .csx files intellisence and coloring doesn't work.
```CSharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Host.MetadataServiceFactory.Service.<>c__DisplayClass1_0.<.ctor>b__0(String path, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.MetadataReferenceCache.ReferenceSet.GetAddOrUpdate(String path, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.MetadataReferenceCache.GetReference(String path, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.MetadataServiceFactory.Service.GetReference(String resolvedPath, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.WorkspaceMetadataFileReferenceResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveReferenceDirective(String reference, Location location, TCompilation compilation)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.HasMissingReferences(Compilation compilation, IReadOnlyList`1 metadataReferences)
   at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(?)
   at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(?)
```

**Comment by aelij** [comment]
* Regarding `STAThread`, I switched from the WPF dispatcher to a generic message pump implementation (for cross-platform support). I'll set the thread to STA in the next version.
* "In a different script" - do you mean a one referenced using `#load`?

**Comment by aelij** [comment]
For the time being, if you need an STA thread, you can use:

```csharp
var thread = new Thread(() =>
{
    // code here
});
thread.SetApartmentState(ApartmentState.STA);
thread.Start();
thread.Join();
```

**Comment by SlowLogicBoy** [comment]
> "In a different script" - do you mean a one referenced using #load?

Yes

>For the time being, if you need an STA thread, you can use:
`var thread = new Thread(() =>
{
    // code here
});
thread.SetApartmentState(ApartmentState.STA);
thread.Start();
thread.Join();`

for this I get:
`A task was canceled.`

**Comment by aelij** [comment]
Stack trace? It works for me.

**Comment by SlowLogicBoy** [comment]
StackTrace is empty :/
Here is a full dump :)
https://gist.github.com/SlowLogicBoy/30be628431859c6de461bf4aaa5f63b3

**Comment by SlowLogicBoy** [comment]
Nvm got it working with
```CSharp
var thread = new Thread(Main);
thread.SetApartmentState(ApartmentState.STA);
thread.Start();
thread.Join();
```
as you suggested, it appears I was creating some STA stuff outside `Main`

**Comment by SlowLogicBoy** [comment]
>in some .csx files intellisence and coloring doesn't work.

I suspect something with `#r` and `#load` is wrong, because if I remove them, save file and load it again coloring comes back.

**Comment by aelij** [comment]
I'd appreciate it if you could send me the code. It does not repro for me.

**Comment by SlowLogicBoy** [comment]
Try referencing something from your assemblies:
`#r "D:\Code\Eto\BuildOutput\net45\Release\Eto.dll"`
after I remove all #r with full paths, it fixes itself :?

**Comment by aelij** [comment]
It works for me...

**Comment by SlowLogicBoy** [comment]
Here is my file:
https://gist.github.com/SlowLogicBoy/4107783518212053017a713d16507dc0

**Comment by aelij** [comment]
And `Base.csx`? :)

**Comment by SlowLogicBoy** [comment]
Here ya go:
https://gist.github.com/SlowLogicBoy/7564306e23eff22e69cde705515e2671

**Comment by aelij** [comment]
Everything compiles fine here. No colorization issue. I'll check from another machine as well. What's your setup (OS, etc.)?

**Comment by SlowLogicBoy** [comment]
Windows 10 Enterprise x64,
I have I think all latest .net frameworks including .net core sdk 2.0

It compiles for me too, just the coloring doesn't work, `Base.csx` is fine, but `EtoBase.csx` is messed up.

**Comment by SlowLogicBoy** [comment]
![image](https://user-images.githubusercontent.com/3121637/29913147-ebaf813e-8e3c-11e7-8775-9390862b78a5.png)

**Comment by aelij** [comment]
BTW, in the future it's better to open separate issues.

**Comment by SlowLogicBoy** [comment]
Ah yea sorry

**Comment by aelij** [comment]
I'm closing this as I've restored the WPF dispatcher (0d4f9a32ad33359262654c6adb4928c316f04041). Please check the Eto issue in the upcoming release (13.1) and open another issue if it still happens.
