### ISSUE TITLE
RoslynPad nuget packages cannot be used from signed assemblies

### ISSUE THREAD

**Issue by southpolenator** [aelij/RoslynPad#146]
Exception is thrown when referencing RoslynPad from signed assembly:

```
System.IO.FileLoadException: Could not load file or assembly 'RoslynPad.Roslyn, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'RoslynPad.Roslyn, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by aelij** [comment]
Some of the dependencies I use are not strong named, so it would be a hassle to get all of the RP assemblies to be strong named. Microsoft’s [guidance](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) also discourages this.

Have you considered using https://github.com/dsplaisted/strongnamer?

**Comment by southpolenator** [comment]
I tried adding StongNamer nuget, but without luck :(
As soon as a reference to RoslynPad.Editor.Windows is added, build error pops up:
```
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018: The "StrongNamer.AddStrongName" task failed unexpectedly.
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at Mono.Cecil.PE.ImageReader.ReadImage()
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, StrongNameKeyPair key, StrongNamerAssemblyResolver resolver)
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at StrongNamer.AddStrongName.Execute()
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>Projects\RoslynPadTest\packages\StrongNamer.0.0.6\build\StrongNamer.targets(9,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by aelij** [comment]
Seems like there's an issue with assembly resolution. Perhaps you could open an issue in the StrongNamer repo.
