### ISSUE TITLE
Mac OS System.TypeInitializationException

### ISSUE THREAD

**Issue by skandyrocks** [aelij/RoslynPad#183]
I build RoslynPad on Mac OS (thanks for the instructions). Build runs through smoothly but everytime when I try to run RoslynPad.NetCore I got this error right on startup:

I used mono 5.4.1 and .netcore 2.0 - result is the same

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Avalonia.Threading.AvaloniaScheduler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.Concurrency.ConcurrencyAbstractionLayer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.PlatformServices.PlatformEnlightenmentProvider' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.6000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider.CreatePlatformProvider()
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayer.Initialize()
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayer..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.PlatformServices.SystemClock.Register(LocalScheduler scheduler)
   at Avalonia.Threading.AvaloniaScheduler..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Application.RegisterServices()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at RoslynPad.Program.Main(String[] args) in /Users/skandy/workspace/tmp/roslynpad/roslynpad/src/RoslynPad.NetCore/Program.cs:line 10
Abort trap: 6
```

**Comment by aelij** [comment]
RoslynPad on Mac is alpha :) I've only tested it using .NET Core 1.1. But a newer version that uses 2.0 is in the works.

**Comment by pietgk** [comment]
I Get the same on .NET core 1.1.2 after following the Readme (brew, clone, restore run).

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Avalonia.Threading.AvaloniaScheduler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.Concurrency.ConcurrencyAbstractionLayer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.PlatformServices.PlatformEnlightenmentProvider' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.6000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider.CreatePlatformProvider()
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayer.Initialize()
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayer..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.PlatformServices.SystemClock.Register(LocalScheduler scheduler)
   at Avalonia.Threading.AvaloniaScheduler..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Application.RegisterServices()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at RoslynPad.Program.Main(String[] args) in /Users/grop/dev/RoslynPad/roslynpad/src/RoslynPad.NetCore/Program.cs:line 10
```

**Comment by ptupitsyn** [comment]
I get the same thing on Ubuntu

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Avalonia.Threading.AvaloniaScheduler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.Concurrency.ConcurrencyAbstractionLayer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.PlatformServices.PlatformEnlightenmentProvider' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.6000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider.CreatePlatformProvider()
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayer.Initialize()
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayer..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.PlatformServices.SystemClock.Register(LocalScheduler scheduler)
   at Avalonia.Threading.AvaloniaScheduler..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Application.RegisterServices()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at RoslynPad.Program.Main(String[] args) in /home/pavel/w/roslynpad/RoslynPad/src/RoslynPad.NetCore/Program.cs:line 10
```

**Comment by aelij** [comment]
Thanks to everyone who are trying out RoslynPad on Mac/Linux!

I've just pushed a few commits which should allow you to run RP using .NET Core 2.0 (only). Note this is still very much an alpha version with lots of missing functionality. The next release (v14) will feature a beta cross-platform version. Stay tuned!

**Comment by jhgoodwin** [comment]
I tried the version from commit 67e34dd71008d54d60431144506160b334ac1147 which seems to be the one you're talking about aelij, but it still gives the same message.

```
$ dotnet run
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
NSEVENT
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.0.6 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.1.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.0.6 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.1.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by aelij** [comment]
The README needs to be updated - you need .NET Core 2.x
