### ISSUE TITLE
Type load error on start

### ISSUE THREAD

**Issue by jakesays** [aelij/RoslynPad#196]
I just pulled master, built, ran, and I get this exception:

**System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()"**

It happens on line 91 in RoslynHost.cs

The content of LoaderExceptions is:

**Could not load type 'Roslyn.Utilities.PooledObject`1' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.**

**Comment by aelij** [comment]
Hmm, I did a clean pull and didn't get that. Can anyone else verify this?

**Comment by paralaxsd** [comment]
Cannot reproduce the issue when running latest master from VS 15.7.1 (rebuilt + tested debug and release builds)

**Comment by jakesays** [comment]
@aelij @paralaxsd I'll give it another try. I'm on VS 15.7.0

**Comment by jakesays** [comment]
Still getting it, although I also encountered this issue:

**No default constructor found for type 'RoslynPad.MainWindow'. You can use the Arguments or FactoryMethod directives to construct this type.**

at start. I recall getting this last time as well. I just made the MainWindow ctor public to get around it.
What I don't understand is why the internal ctor works for you guys.

**Comment by jakesays** [comment]
I deleted my repo and started over. This time it built and started fine. No clue..
Thanks!

**Comment by PtrStruct** [comment]
I am getting the same issue, I was told to get a clean clone but isnt that just cloning it into Visual Studio or am I missing something?

**Comment by jakesays** [comment]
@PtrStruct Delete your entire source tree and start over.

**Comment by rtigithub** [comment]
I created a new clone of the master branch.  The build succeeds for all 14 projects with 3 warnings:  RoslynPad.Host32, RoslynPad.Host64, RoslynPad; Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved.  
When I try to run I get System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at RoslynPad.Roslyn.RoslynHost.<>c.<.ctor>b__20_0(Assembly x) in F:\Users\passp\Source\Repos\RoslynPadMaster\src\RoslynPad.Roslyn\RoslynHost.cs:line 91
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at RoslynPad.Roslyn.RoslynHost..ctor(NuGetConfiguration nuGetConfiguration, IEnumerable`1 additionalAssemblies, RoslynHostReferences references) in F:\Users\passp\Source\Repos\RoslynPadMaster\src\RoslynPad.Roslyn\RoslynHost.cs:line 94
   at RoslynPad.UI.MainViewModelBase.<InitializeInternal>b__37_0() in F:\Users\passp\Source\Repos\RoslynPadMaster\src\RoslynPad.Common.UI\ViewModels\MainViewModelBase.cs:line 117
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by rtigithub** [comment]
I also performed Tools | Options | NuGet Package Manager | General | Clear All NuGet Cache(s). Same result: "Unable to load one or more of the requested types..."
