### ISSUE TITLE
Unable to load the service index for source nuget

### ISSUE THREAD

**Issue by tkouba** [aelij/RoslynPad#202]
Unhandled exception is thrown for visualstudio.com hosted package feed with authorization.

`System.InvalidOperationException: Unable to load the service index for source https://xyz.pkgs.visualstudio.com/_packaging/xyz/nuget/v3/index.json. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://xyz.pkgs.visualstudio.com/_packaging/xyz/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at async NuGet.Protocol.HttpSource.<>c__DisplayClass12_0'1.<GetAsync>b__0[](?)
   at async NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[](?)
   at async NuGet.Protocol.HttpSource.GetAsync[](?)
   at async NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(?)
   --- End of inner exception stack trace ---
   at async NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(?)
   at async NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(?)
   at async NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[](?)
   at async NuGet.Protocol.DependencyInfoResourceV3Provider.TryCreate(?)
   at async NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[](?)
   at async NuGet.PackageManagement.ResolverGather.<>c__DisplayClass31_0.<InitializeResourcesAsync>b__0(?)
   at async NuGet.PackageManagement.ResolverGather.InitializeResourcesAsync(?)
   at async NuGet.PackageManagement.ResolverGather.GatherAsync(?)
   at async NuGet.PackageManagement.ResolverGather.GatherAsync(?)
   at async NuGet.PackageManagement.NuGetPackageManager.PreviewInstallPackageAsync(?)
   --- End of inner exception stack trace ---
   at async NuGet.PackageManagement.NuGetPackageManager.PreviewInstallPackageAsync(?)
   at async NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(?)
   at async NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(?)
   at async RoslynPad.UI.NuGetViewModel.InstallPackage(?)
   at async RoslynPad.UI.NuGetDocumentViewModel.InstallPackage(?)
   at async RoslynPad.Utilities.DelegateCommand'1.ExecuteAsync[](?)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by sopelt** [comment]
This happens for private myget.org feeds as well (that are not api-key/preauthenticated).
It would be nice if it worked or if the feed could just be ignored on such faults.

**Comment by aelij** [comment]
As you can see I'm using the NuGet API. But I'll see what I can do. I'm in the process of completely rewriting RP's NuGet support using lock files, at which point I may just invoke NuGet.exe. When you use `nuget restore` (or `dotnet restore`) does it properly request credentials in your scenarios?

**Comment by sopelt** [comment]
Well @aelij ... this is somewhat strange. Everything works as expected in VS2017 but the same user from a dev command line also gets faults when trying to install/restore when such a feed is present: 

```nuget install Newtonsoft.Json
Feeds used:
  https://api.nuget.org/v3/index.json
  https://www.myget.org/F/.../auth/.../api/v3/index.json
  https://www.myget.org/F/.../api/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

  GET https://www.myget.org/F/.../api/v3/registration1/newtonsoft.json/index.json
  GET https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.json
  GET https://www.myget.org/F/.../auth/.../api/v3/registration1/newtonsoft.json/index.json
Please provide credentials for: https://www.myget.org/F/.../api/v3/index.json
UserName: Cannot prompt for input in non-interactive mode.
  Unauthorized https://www.myget.org/F/.../api/v3/registration1/newtonsoft.json/index.json 263ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.json 651ms
  NotFound https://www.myget.org/F/.../auth/.../api/v3/registration1/newtonsoft.json/index.json 667ms
An error occurred while retrieving package metadata for 'Newtonsoft.Json' from source '...'.
  Response status code does not indicate success: 401 (Unauthorized).
```

I have myget credentials in Windows Credential Manager so I assume that is where VS is getting them from - but who knows.

That will be quite hard to do anything for that situation ...

**Comment by aelij** [comment]
@sopelt I think you can use [credential providers](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers) in this scenario. I'll have to investigate how they work with the NuGet API, although I may use use nuget.exe in my rewrite.

**Comment by aelij** [comment]
The new NuGet reference support (committed, not yet published - v14) uses the NuGet restore command, which should also enable interactive login as well as be tolerant to failures. I welcome you to clone the repo and give it try.
