### ISSUE TITLE
RoslynPad.Editor.Windows missing dependency System.Reactive.Core

### ISSUE THREAD

**Issue by YanerTavuz** [aelij/RoslynPad#252]
My project uses a branch of 

> RoslynPad.Editor.Windows 1.0.4

 and when running the application we get an exception saying that assembly System.Reactive.Core is missing. 
There is a dependency to System.Reactive.Linq, but this does not include System.Reactive.Core.
Easily solved by installing System.Reactive.Core to the project, but should be done automatically as a dependency.

Exception:

FileNotFoundException: [Could not load file or assembly 'System.Reactive.Core, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.]

Stack trace:

   at RoslynPad.Editor.RoslynSemanticHighlighter..ctor(TextView textView, IDocument document, DocumentId documentId, IRoslynHost roslynHost, IClassificationHighlightColors highlightColors)

   at RoslynPad.Editor.RoslynHighlightingColorizer.CreateHighlighter(TextView textView, TextDocument document)

   at ICSharpCode.AvalonEdit.Highlighting.HighlightingColorizer.RegisterServices(TextView textView)

   at ICSharpCode.AvalonEdit.Highlighting.HighlightingColorizer.OnAddToTextView(TextView textView)

   at ICSharpCode.AvalonEdit.Rendering.ColorizingTransformer.ICSharpCode.AvalonEdit.Rendering.ITextViewConnect.AddToTextView(TextView textView)

   at ICSharpCode.AvalonEdit.Rendering.TextView.LineTransformer_Added(IVisualLineTransformer lineTransformer)

   at ICSharpCode.AvalonEdit.Utils.ObserveAddRemoveCollection`1.InsertItem(Int32 index, T item)

   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)

   at WebAPIEditor.Code.Controls.WebAPICodeEditor.Initialize(IWebApiCodeHost codeHost, IClassificationHighlightColors highlightColors, CodeDocumentFile documentFile) in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Code\Controls\WebAPICodeEditor.cs:line 127

   at WebAPIEditor.Views.WebAPICodeDocumentEditorView.InitializeCodeEditor() in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Views\WebAPICodeDocumentEditorView.xaml.cs:line 128

   at WebAPIEditor.Controllers.WebApiModuleController.CreateDocumentViewModel(CodeDocumentFile document) in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Controllers\WebApiModuleController.cs:line 152

   at WebAPIEditor.Controllers.WebApiModuleController.CreateDocumentDataModel(IDocumentFile documentFile) in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Controllers\WebApiModuleController.cs:line 135

   at System.Waf.Foundation.SynchronizingCollectionCore`2.CreateItem(TOriginal oldItem)

   at System.Waf.Foundation.SynchronizingCollectionCore`2.OriginalCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)

   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)

   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)

   at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)

   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)

   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)

   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)

   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)

   at System.Collections.ObjectModel.Collection`1.Add(T item)

   at WebAPIEditor.Code.Services.DocumentService.AddDocument(IDocumentFile document, Boolean insertInAlphabeticalOrder) in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Code\Services\DocumentService.cs:line 87

   at WebAPIEditor.Code.Services.ProjectWorkspaceService.<OpenAsync>d__13.MoveNext() in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Code\Services\ProjectWorkspaceService.cs:line 79

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at WebAPIEditor.Controllers.WebApiController.<>c__DisplayClass42_0.<<OpenWebApiDefinition>b__0>d.MoveNext() in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Controllers\WebApiController.cs:line 273

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at iCore.Common.Presentation.Services.InteractionService.<WaitForBackgroundAction>d__28`1.MoveNext() in F:\ETWork\4.10.Servicing\Common\Assemblies\iCore.Common.Presentation\Services\InteractionService.cs:line 259

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at WebAPIEditor.Controllers.WebApiController.OpenWebApiDefinition(IWebApi entity) in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Controllers\WebApiController.cs:line 268

   at WebAPIEditor.Controllers.WebApiController.OnOpen(Object parameter) in F:\ETWork\4.10.Servicing\iCore Tools\WebAPITool\WebAPIEditor\Controllers\WebApiController.cs:line 250

**Comment by aelij** [comment]
Thanks for the report, but I'm closing as Reactive won't be used at all in the next version.
