### ISSUE TITLE
Upgrading to Roslyn 14.1 - Causing Unhandled Excpetion

### ISSUE THREAD

**Issue by Page-Not-Found** [aelij/RoslynPad#266]
**Error Details**
[Main Instruction]
Unhandled Exception
[Content]
System.InvalidOperationException: No platform version selected
   at RoslynPad.Hosting.AssemblyExecutionHost.get_PlatformVersion()
   at RoslynPad.Hosting.AssemblyExecutionHost.CreateRuntimeConfig()
   at RoslynPad.Hosting.AssemblyExecutionHost.set_Platform(ExecutionPlatform value)
   at RoslynPad.UI.OpenDocumentViewModel.set_Platform(ExecutionPlatform value)
   at RoslynPad.UI.MainViewModelBase.<LoadAutoSavedDocuments>b__38_0(String x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at NuGet.Packaging.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at async RoslynPad.UI.MainViewModelBase.OpenAutoSavedDocuments(?)
   at async RoslynPad.UI.MainViewModelBase.InitializeInternal(?)
   at async RoslynPad.UI.MainViewModelBase.Initialize(?)
[Buttons]
   [Header=C_lose, Content=] 

Additional Information:
**OS:** Windows 7 Enterprise

**Comment by aelij** [comment]
Can you please list the directories you have under `C:\Program Files\dotnet\shared`?
Also, please make sure you use 14.1 and not 14, which had this exact bug (#251).

**Comment by Page-Not-Found** [comment]
To answer the version question. Yes I did download new package from official site.

**Comment by Page-Not-Found** [comment]
![image](https://user-images.githubusercontent.com/635337/55647834-ad009a00-57ac-11e9-8f66-8fa7e6c33628.png)

**Comment by Page-Not-Found** [comment]
Closed by mistake. Reopening.

**Comment by Page-Not-Found** [comment]
@aelij I had a screenshot in this https://github.com/aelij/RoslynPad/issues/266#issuecomment-480372098

**Comment by Page-Not-Found** [comment]
@aelij Installign Dotnet Core 2.2 Did the Trick
