### ISSUE TITLE
RoslynPad 14.1 not working on Windows 10: throws "Cloud provider not running error"

### ISSUE THREAD

**Issue by madhub** [aelij/RoslynPad#288]
I downloaded RoslynPad  from Windows store & tried to run it, throws "Cloud provider not running error". Also tried downloading from GitHub, same error.

![image](https://user-images.githubusercontent.com/8907962/58685997-22e34500-839b-11e9-9bba-1e3476345fc6.png)

**Comment by ohadschn** [comment]
Sounds like a OneDrive issue. What happens if you move your RoslynPad Documents folder to some other folder (outside your OneDrive folder)? You can do it using the right-most button at the bottom of the Documents pane (on the left).

**Comment by madhub** [comment]
Yes, it works once I change the location. But error is still shown in the bottom pane 
One more observation , when my document  was pointing to one drive location , nothing was working (no IntelliSense ).

Some suggestion 
- it is better to move "open file" , change document location to top. It is not easy discoverable in the current layout.
- if document location is not accessible , everything still should work , while saving provide option to save in different location.

Madhu

**Comment by aelij** [comment]
@madhub Can you please click the View details button, then hit <kbd>Ctrl+C</kbd> and paste the stack trace here?

**Comment by madhub** [comment]
Here is the exception details


[Main Instruction]
Unhandled Exception


[Content]
NuGet.Configuration.NuGetConfigurationException: NuGet.Config is not valid XML. Path: 'C:\Users\bs_ma\AppData\Roaming\NuGet\NuGet.Config'. ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.Configuration.XmlUtility.GetDocument(String fullPath)
   at NuGet.Configuration.XmlUtility.GetOrCreateDocument(XDocument content, String fullPath)
   at NuGet.Configuration.Settings.<>c__DisplayClass23_0.<.ctor>b__0()
   at NuGet.Configuration.Settings.<>c__DisplayClass82_0.<ExecuteSynchronized>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Configuration.Settings.<>c__DisplayClass82_0.<ExecuteSynchronized>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Configuration.Settings..ctor(String root, String fileName, Boolean isMachineWideSettings)
   at NuGet.Configuration.Settings.ReadSettings(String root, String settingsPath, Boolean isMachineWideSettings)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(List`1 validSettingFiles, String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean useTestingGlobalPath)
   at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadAppDataSettings, Boolean useTestingGlobalPath)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadAppDataSettings, Boolean useTestingGlobalPath)
   at RoslynPad.UI.NuGetViewModel..ctor()
   at RoslynPad.UI.NuGetViewModel.CreateRestoreParams()
   at async RoslynPad.UI.NuGetDocumentViewModel.RefreshPackagesAsync(?)




[Buttons]
   [Header=C_lose, Content=]

**Comment by rossdonald** [comment]
@madhub I had the same issue and I deleted the config file from the LocalCache and it fixed it up for me.
Here is the instructions
https://github.com/aelij/RoslynPad/issues/170#issuecomment-497207816

**Comment by aelij** [comment]
This should be fixed in the latest version.
