### ISSUE TITLE
Error on start for MacOS

### ISSUE THREAD

**Issue by phillijw** [aelij/RoslynPad#304]
Current master branch (commit 5081700dc2a4c243ec4e9267b49f4a667a528b7c)

```
/usr/local/share/dotnet/dotnet /Users/joe/repos/RoslynPad/src/RoslynPad.Avalonia/bin/Debug/netcoreapp2.2/RoslynPad.dll
Assertion Failed
Not on UI thread

   at RoslynPad.UI.Utilities.DebugEx.AssertIsUiThread() in /Users/joe/repos/RoslynPad/src/RoslynPad.Common.UI/Utilities/DebugEx.cs:line 11
   at RoslynPad.UI.NuGetDocumentViewModel.UpdateLibraries(IReadOnlyList`1 libraries) in /Users/joe/repos/RoslynPad/src/RoslynPad.Common.UI/ViewModels/NuGetViewModel.cs:line 507
   at RoslynPad.UI.OpenDocumentViewModel.UpdatePackages() in /Users/joe/repos/RoslynPad/src/RoslynPad.Common.UI/ViewModels/OpenDocumentViewModel.cs:line 729
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RoslynPad.UI.OpenDocumentViewModel.UpdatePackages()
   at RoslynPad.UI.OpenDocumentViewModel.Initialize(DocumentId documentId, Action`1 onError, Func`1 getSelection, IDisposable viewDisposable) in /Users/joe/repos/RoslynPad/src/RoslynPad.Common.UI/ViewModels/OpenDocumentViewModel.cs:line 614
   at RoslynPad.DocumentView.OnDataContextChanged(Object sender, EventArgs args) in /Users/joe/repos/RoslynPad/src/RoslynPad.Avalonia/DocumentView.xaml.cs:line 65
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RoslynPad.DocumentView.OnDataContextChanged(Object sender, EventArgs args)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 505
   at Avalonia.AvaloniaObject.set_InheritanceParent(IAvaloniaObject value) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 135
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild() in D:\a\1\s\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 242
   at Avalonia.Controls.ItemsControl.OnContainersMaterialized(ItemContainerEventArgs e) in D:\a\1\s\src\Avalonia.Controls\ItemsControl.cs:line 254
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnContainersMaterialized(ItemContainerEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 386
   at Avalonia.Controls.Generators.ItemContainerGenerator.Materialize(Int32 index, Object item, IMemberSelector selector) in D:\a\1\s\src\Avalonia.Controls\Generators\ItemContainerGenerator.cs:line 68
   at Avalonia.Controls.Presenters.CarouselPresenter.GetOrCreateContainer(Int32 index) in D:\a\1\s\src\Avalonia.Controls\Presenters\CarouselPresenter.cs:line 207
   at Avalonia.Controls.Presenters.CarouselPresenter.MoveToPage(Int32 fromIndex, Int32 toIndex) in D:\a\1\s\src\Avalonia.Controls\Presenters\CarouselPresenter.cs:line 171
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Avalonia.Controls.Presenters.CarouselPresenter.MoveToPage(Int32 fromIndex, Int32 toIndex)
   at Avalonia.Controls.Presenters.CarouselPresenter.SelectedIndexChanged(AvaloniaPropertyChangedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Presenters\CarouselPresenter.cs:line 226
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Avalonia.Controls.Presenters.CarouselPresenter.SelectedIndexChanged(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 505
   at Avalonia.Controls.Presenters.CarouselPresenter.set_SelectedIndex(Int32 value) in D:\a\1\s\src\Avalonia.Controls\Presenters\CarouselPresenter.cs:line 85
   at Avalonia.AvaloniaObject.<>c__DisplayClass49_0.<SetDirectValue>g__Set|0() in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 664
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 507
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 144
   at Avalonia.Controls.Primitives.SelectingItemsControl.<set_SelectedIndex>b__25_0(Int32 val, Int32& backing, Action`1 notifyWrapper) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 161
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 553
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 140
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedIndex(Int32 value) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 176
   at Avalonia.AvaloniaObject.<>c__DisplayClass49_0.<SetDirectValue>g__Set|0() in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 664
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 507
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 144
   at Avalonia.Controls.Primitives.SelectingItemsControl.<set_SelectedIndex>b__25_0(Int32 val, Int32& backing, Action`1 notifyWrapper) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 161
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 553
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 140
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedIndex(Int32 value) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 176
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in D:\a\1\s\src\Avalonia.Base\Reactive\LightweightObservableBase.cs:line 132
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs) in D:\a\1\s\src\Avalonia.Base\Utilities\WeakSubscriptionManager.cs:line 187
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at RoslynPad.UI.MainViewModelBase.CreateNewDocument() in /Users/joe/repos/RoslynPad/src/RoslynPad.Common.UI/ViewModels/MainViewModelBase.cs:line 378
   at RoslynPad.UI.MainViewModelBase.OpenAutoSavedDocuments() in /Users/joe/repos/RoslynPad/src/RoslynPad.Common.UI/ViewModels/MainViewModelBase.cs:line 162
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Boolean priorityContainsMeaningfulValue) in /Users/vsts/agent/2.141.1/work/1/s/src/Avalonia.Native/PlatformThreadingInterface.cs:line 42
   at Avalonia.Native.Interop.IAvnSignaledCallbackShadow.IAvnSignaledCallbackVtbl.Signaled(IntPtr thisObject, Int32 param0, Byte param1) in /Users/vsts/agent/2.141.1/work/1/s/src/Avalonia.Native/obj/Release/netstandard2.0/SharpGen/Generated/Interfaces.cs:line 801
   at Avalonia.Native.Interop.IAvnPlatformThreadingInterface.RunLoop(IAvnLoopCancellation cancel) in /Users/vsts/agent/2.141.1/work/1/s/src/Avalonia.Native/obj/Release/netstandard2.0/SharpGen/Generated/Interfaces.cs:line 695
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /Users/vsts/agent/2.141.1/work/1/s/src/Avalonia.Native/PlatformThreadingInterface.cs:line 77
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Application.Run(Window mainWindow) in D:\a\1\s\src\Avalonia.Controls\Application.cs:line 237
   at RoslynPad.Program.Main(String[] args) in /Users/joe/repos/RoslynPad/src/RoslynPad.Avalonia/Program.cs:line 11

Process finished with exit code 6.
```

If I comment out `DebugEx.AssertIsUiThread();` it will run (although the UI looks very bad). I'm not sure what this code is doing or what it has to do with the UI.

**Comment by aelij** [comment]
Thanks for this bug report but this entire code path is being removed for the next version :)

**Comment by phillijw** [comment]
@aelij Do you happen to have a branch available for "next version" that I could run for the time being?

**Comment by aelij** [comment]
It's not pushed yet. Maybe next week
But your workaround seems reasonable. The UI looking "very bad" might be because I haven't invested in the xplat UX yet. Can you share a screenshot?

**Comment by phillijw** [comment]
This is how it looks when it opens:
![image](https://user-images.githubusercontent.com/467889/66756945-ab511680-ee60-11e9-90d2-06481c66ac44.png)

This is how it looks at full screen:
![image](https://user-images.githubusercontent.com/467889/66756998-c9b71200-ee60-11e9-9cf4-6f4a9de2f9da.png)

**Comment by aelij** [comment]
Yeah that's the current state of things :) I'm waiting for Avalonia's API to stabilize and then I'll invest more in the xplat UI.

**Comment by gabrbuiv** [comment]
Hey. Was this issue fixed? I'm having the same error now with RoslyPad 14.
