### ISSUE TITLE
 NuGet.Config is not valid XML

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#320]
The following appears as a red error at the bottom on startup:
```
NuGet.Configuration.NuGetConfigurationException: NuGet.Config is not valid XML. Path: 'C:\Users\ohad1\AppData\Roaming\NuGet\NuGet.Config'. ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.Configuration.XmlUtility.GetDocument(String fullPath)
   at NuGet.Configuration.XmlUtility.GetOrCreateDocument(XDocument content, String fullPath)
   at NuGet.Configuration.Settings.<>c__DisplayClass23_0.<.ctor>b__0()
   at NuGet.Configuration.Settings.<>c__DisplayClass82_0.<ExecuteSynchronized>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Configuration.Settings.<>c__DisplayClass82_0.<ExecuteSynchronized>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Configuration.Settings..ctor(String root, String fileName, Boolean isMachineWideSettings)
   at NuGet.Configuration.Settings.ReadSettings(String root, String settingsPath, Boolean isMachineWideSettings)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(List`1 validSettingFiles, String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean useTestingGlobalPath)
   at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadAppDataSettings, Boolean useTestingGlobalPath)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadAppDataSettings, Boolean useTestingGlobalPath)
   at RoslynPad.UI.NuGetViewModel..ctor()
   at RoslynPad.UI.NuGetViewModel.CreateRestoreParams()
   at async RoslynPad.UI.NuGetDocumentViewModel.RefreshPackagesAsync(?)
```

Trying to compile Core x64 results in:
`FileNotFoundException: Could not find file 'C:\Users\ohad1\AppData\Local\Temp\RoslynPad\Build\7a67f882-88d1-4097-9f83-da34b6f2fe4d\nuget\project.assets.json'.`

Trying to compile Desktop (x86 or x64) results in errors like:
1. `CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.`
1. `CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)`

The XML from the original error (`C:\Users\ohad1\AppData\Roaming\NuGet\NuGet.Config`) looks fine to me, tried removing the UTF-8 BOM, removing the XML declaration, nothing changed. Passed Notepad++ XML Tools validation. I even executed `Document.Load("C:\Users\ohad1\AppData\Roaming\NuGet\NuGet.Config")` from LinqPad and it worked, so I suspect this file is not the true offender.

**Comment by aelij** [comment]
This should be fixed in master.

**Comment by StingyJack** [comment]
@aelij  - which version would this be fixed in? I just started getting the error with v14.1.

**Comment by aelij** [comment]
As I said, it's only in source at the moment. Will be in v15 when I publish it.

**Comment by StingyJack** [comment]
This can be fixed by "Reset" the app. 

Open "Add or Remove Programs", search for RoslynPad
![image](https://user-images.githubusercontent.com/15381181/79059704-3615a100-7c4b-11ea-823d-4c14958464af.png)
Click "Advanced options", then scroll down and click the Reset button.
![image](https://user-images.githubusercontent.com/15381181/79059713-4e85bb80-7c4b-11ea-86d1-1867fd171623.png)
