### ISSUE TITLE
Not compatible with Microsoft.CodeAnalysis >3.6.0

### ISSUE THREAD

**Issue by FroggieFrog** [aelij/RoslynPad#389]
**Describe the bug**
The project (specific the NuGet packages) are not compatible when a version `>3.6.0` of the `Microsoft.CodeAnalysis.*` packages is referenced. But the page on NuGet shows it is compatible with version `>=3.6.0`.
So the component can not be used in a project which requires an up-to-date version of `Microsoft.CodeAnalysis.*` e.g. `3.9.0`.
At runtime there is a `System.Reflection.ReflectionTypeLoadException`:
```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Method 'CanNavigateToSpan' in type 'RoslynPad.Roslyn.Navigation.DocumentNavigationService' from assembly 'RoslynPad.Roslyn, Version=3.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetChangeSignatureOptions' in type 'RoslynPad.Roslyn.LanguageServices.ChangeSignature.ChangeSignatureOptionsService' from assembly 'RoslynPad.Roslyn, Version=3.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Could not load type 'Microsoft.CodeAnalysis.Diagnostics.IHostDiagnosticAnalyzerPackageProvider' from assembly 'Microsoft.CodeAnalysis.Features, Version=3.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=3.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at RoslynPad.Roslyn.RoslynHost.<>c.<.ctor>b__22_0(Assembly x)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at RoslynPad.Roslyn.RoslynHost..ctor(IEnumerable`1 additionalAssemblies, RoslynHostReferences references, Nullable`1 disabledDiagnostics)
```

_Maybe the NuGet packages (`RoslynPad.Roslyn`) are not up-to-date?_

**To Reproduce**
Add references to the newer versions in project file.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RoslynPad.Editor.Windows" Version="1.2.0" />
    <PackageReference Include="RoslynPad.Roslyn" Version="3.6.0" />
    <PackageReference Include="RoslynPad.Roslyn.Windows" Version="3.6.0" />

    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="3.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="3.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="3.9.0" />
  </ItemGroup>

</Project>
```
**Expected behavior**
The NuGet packages are compatibel with  up-to-date versions of `Microsoft.CodeAnalysis.*`.
**Version**
- OS: Windows 10 20H2
- Build (or commit ID if built from source): 3.6.0

**Comment by VPKSoft** [comment]
Hi,
I'm getting the same error too. This seems to be happening in the `RoslynPad\src\RoslynPad.Roslyn\RoslynHost.cs` file when the assembly type collection at line 76:
```cs
var partTypes = assemblies
    .SelectMany(x => x.DefinedTypes)
    .Select(x => x.AsType());
```
gets enumerated at line 81 in the same file.

**Comment by aelij** [comment]
This is by design, as stated in the README:

> RoslynPad.Roslyn* package versions will correspond to Roslyn's.

RP uses Roslyn internals so it much match exactly.
