### ISSUE TITLE
RoslynPad downloaded from Microsoft Store not starting

### ISSUE THREAD

**Issue by hjung7** [aelij/RoslynPad#77]
Here is the error output from windows event viewer:

```
Application: RoslynPad.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[], Int32, Int32)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(System.Xml.XmlReader, System.Xml.Linq.LoadOptions)
   at NuGet.Configuration.XmlUtility.LoadSafe(System.IO.Stream, System.Xml.Linq.LoadOptions)
   at NuGet.Configuration.XmlUtility.GetDocument(System.String)
   at NuGet.Configuration.XmlUtility.GetOrCreateDocument(System.Xml.Linq.XDocument, System.String)
   at NuGet.Configuration.Settings+<>c__DisplayClass19_0.<.ctor>b__0()
   at NuGet.Configuration.Settings.ExecuteSynchronizedCore(System.Action)

Exception Info: NuGet.Configuration.NuGetConfigurationException
   at NuGet.Configuration.Settings.ExecuteSynchronizedCore(System.Action)
   at NuGet.Configuration.Settings..ctor(System.String, System.String, Boolean)
   at NuGet.Configuration.Settings.ReadSettings(System.String, System.String, Boolean)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(System.Collections.Generic.List`1<NuGet.Configuration.Settings>, System.String, System.String, NuGet.Configuration.IMachineWideSettings, Boolean)
   at NuGet.Configuration.Settings.LoadDefaultSettings(System.String, System.String, NuGet.Configuration.IMachineWideSettings, Boolean, Boolean)
   at RoslynPad.UI.NuGetViewModel..ctor()
   at DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Composition.Hosting.Core.LifetimeContext, System.Composition.Hosting.Core.CompositionOperation)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32, System.Composition.Hosting.Core.CompositionOperation, System.Composition.Hosting.Core.CompositeActivator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature+<>c__DisplayClass2.<RewriteActivator>b__0(System.Composition.Hosting.Core.LifetimeContext, System.Composition.Hosting.Core.CompositionOperation)
   at DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Composition.Hosting.Core.LifetimeContext, System.Composition.Hosting.Core.CompositionOperation)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32, System.Composition.Hosting.Core.CompositionOperation, System.Composition.Hosting.Core.CompositeActivator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature+<>c__DisplayClass2.<RewriteActivator>b__0(System.Composition.Hosting.Core.LifetimeContext, System.Composition.Hosting.Core.CompositionOperation)
   at System.Composition.Hosting.Core.CompositionOperation.Run(System.Composition.Hosting.Core.LifetimeContext, System.Composition.Hosting.Core.CompositeActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(System.Composition.Hosting.Core.CompositionContract, System.Object ByRef)
   at System.Composition.CompositionContext.GetExport(System.Composition.Hosting.Core.CompositionContract)
   at RoslynPad.UI.SystemCompositionServiceLocator.DoGetInstance(System.Type, System.String)
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(System.Type, System.String)

Exception Info: Microsoft.Practices.ServiceLocation.ActivationException
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(System.Type, System.String)
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at RoslynPad.MainWindow..ctor()
   at DynamicClass.MainWindowCtor(System.Object[])
   at MS.Internal.Xaml.Runtime.DynamicMethodRuntime.CreateInstanceWithCtor(System.Type, System.Object[])
   at MS.Internal.Xaml.Runtime.DynamicMethodRuntime.CreateInstanceWithCtor(System.Xaml.XamlType, System.Object[])
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(System.Xaml.XamlType, System.Object[])

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at RoslynPad.App.Main()
```

**Comment by aelij** [comment]
Thanks for reporting this!

Does the standalone (zip) version work on your machine?

**Comment by hjung7** [comment]
Yes, standalone (zip) version works fine.

**Comment by aelij** [comment]
Very weird. Would you mind running the following script in RoslynPad and let me know if it throws? (Replace `C:\Path\To\RoslynPad` with the actual path)

```csharp
#r "C:\Path\To\RoslynPad\NuGet.Configuration.dll"

NuGet.Configuration.Settings.LoadDefaultSettings(null, null, null)
```

**Comment by hjung7** [comment]
I suppose you mean in the standalone RoslynPad?
If so, it works fine

**Comment by aelij** [comment]
Thanks for your help. I've tried to make sure errors such as these won't stop RP from loading. Hopefully if this happens in once the next version is published we'll have more to go on.

My guess is that somewhere on your PC there's a corrupt NuGet config file (e.g. containing invalid XML).

**Comment by ohadschn** [comment]
@hjung7 can you still reproduce this? If so, can you create a dump file and upload it somewhere so Eli or I can take a look? [Here's how to configure automatic sump collection upon crash](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). Also check if they happen to already be here:  `C:\Users\UserName\AppData\Local\Microsoft\Windows\WER\ReportArchive`.

@aelij Maybe you have the dumps in the [developer portal](https://blogs.msdn.microsoft.com/stephe/2015/03/30/how-to-use-windows-or-windows-phone-store-app-crash-dumps-found-on-your-dev-portal/)? Or maybe have some more info on HockeyApp?

**Comment by aelij** [comment]
@ohadschn That was the first thing I tried. Unfortunately all it shows there is a partial stack trace. No .cab download, nor the exception message.

In the next version the exception should get caught and sent via HockeyApp.

**Comment by hjung7** [comment]
Here is the link to full dump file.
https://www.dropbox.com/s/k8uaisi6bpuwj76/RoslynPad.exe.64412.dmp?dl=0

**Comment by aelij** [comment]
Thanks, I downloaded the file. You should revoke the link as dump files can contain sensitive information.

The error from the dump is:

> NuGet.Config is not valid XML. Path: 'C:\Users\<user>\AppData\Roaming\NuGet\NuGet.Config'.

where `<user>` is your username. You should check if this file is valid.

**Comment by aelij** [comment]
The `XmlException` is:

> '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

**Comment by hjung7** [comment]
@aelij 
There was indeed a invalid character that didn't show up in the text editor.
After generating a new one I'm seeing following exception in the dump file:
> ConfigurationErrorsException: Configuration system failed to initialize

new dump file:
https://www.dropbox.com/s/fufivhgp61izxsz/RoslynPad.exe.11832.dmp?dl=0

**Comment by aelij** [comment]
I don't understand how it could've happened, but according to the dump, the file
```
C:\Program Files\WindowsApps\34685EliArbel.RoslynPad_0.11.0.0_x86__zyksrj6kvnp3g\RoslynPad.exe.Config
```
is corrupted ("missing root element"). Perhaps this happened when the app crashed?

Anyway, I suggest you remove and reinstall RP.

**Comment by ohadschn** [comment]
@aelij you are such a WinDbg script kiddie...
