### ISSUE TITLE
RoslynPad not opening.

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#88]
When I open RoslynPad it just silently "runs" in the background, and creates new instance every time I open it, no GUI no nothing.
Windows 10 x86 Home
By debugging found out:
```
RoslynHost
	.ctor()
		this._referenceAssembliesPath = RoslynHost.GetReferenceAssembliesPath();// null
	
	private static string GetReferenceAssembliesPath()
		path = "C:\\Program Files\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework"; //doesn't exists
		returns null;
	
	private IEnumerable<string> TryGetFacadeAssemblies()
		string path = Path.Combine(this._referenceAssembliesPath, "Facades"); //Crashes
		
		
Crash message and trace:

"Value cannot be null. Parameter name: path1"
"   at System.IO.Path.Combine(String path1, String path2)
   at RoslynPad.Roslyn.RoslynHost.TryGetFacadeAssemblies()
   at RoslynPad.Roslyn.RoslynHost..ctor(NuGetConfiguration nuGetConfiguration, IEnumerable`1 additionalAssemblies)
   at RoslynPad.UI.MainViewModel..ctor(IServiceLocator serviceLocator, ITelemetryProvider telemetryProvider, ICommandProvider commands, NuGetViewModel nugetViewModel)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass2.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport(Type exportType, String contractName)
   at RoslynPad.UI.SystemCompositionServiceLocator.DoGetInstance(Type serviceType, String key)
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)"
```
I temporarily fixed this by editing an assembly itself, since Visual Studio on this system is a no go.
P.S. Thanks for making this tool, it is now my main place where I live my coding life.

**Comment by aelij** [comment]
Thanks, this was already fixed in #81
